package com.gambitsmp.dimension;

import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.WorldInfo;
import org.bukkit.block.Biome;
import org.bukkit.generator.BiomeProvider;
import org.bukkit.generator.BlockPopulator;
import org.bukkit.generator.ChunkGenerator;

import java.util.List;
import java.util.Random;

/**
 * CardDimension's terrain generator.
 *
 * Deliberately simple: gently rolling hills using a continuous sine/cosine height
 * function (so there are no seams at chunk borders, without needing a full noise
 * library dependency), bedrock at the bottom, stone underneath, and a grass surface.
 *
 * The "purple grass" comes from the world's biome, not from a different block - see
 * CardDimensionManager and the bundled datapack (data/minecraft/worldgen/biome/the_void.json)
 * for how the_void's grass/foliage colors get overridden to purple. This class just
 * places real Material.GRASS_BLOCK.
 *
 * Ore and tree placement happen in the populators below (OrePopulator excludes
 * diamond and adds ancient debris; TreePopulator places sparse spruce/purple-leaf trees).
 */
public class CardDimensionGenerator extends ChunkGenerator {

    private final int surfaceY;

    public CardDimensionGenerator(int surfaceY) {
        this.surfaceY = surfaceY;
    }

    @Override
    public boolean shouldGenerateNoise() {
        return false;
    }

    @Override
    public boolean shouldGenerateSurface() {
        return true;
    }

    @Override
    public boolean shouldGenerateBedrock() {
        return false; // handled inside generateSurface for simplicity
    }

    @Override
    public boolean shouldGenerateCaves() {
        return false;
    }

    @Override
    public boolean shouldGenerateDecorations() {
        return false; // we handle ores/trees ourselves via BlockPopulator
    }

    @Override
    public boolean shouldGenerateMobs() {
        return true;
    }

    @Override
    public void generateSurface(WorldInfo worldInfo, Random random, int chunkX, int chunkZ, ChunkData chunkData) {
        int minY = chunkData.getMinHeight();
        long seed = worldInfo.getSeed();
        // deterministic per-world offsets so terrain doesn't look identical across
        // different server seeds, while still being seam-free between chunks
        double offsetX = (seed % 10000) * 0.001;
        double offsetZ = ((seed / 10000) % 10000) * 0.001;

        for (int x = 0; x < 16; x++) {
            int worldX = (chunkX << 4) + x;
            for (int z = 0; z < 16; z++) {
                int worldZ = (chunkZ << 4) + z;

                double n = Math.sin(worldX * 0.03 + offsetX) * Math.cos(worldZ * 0.03 + offsetZ);
                int height = surfaceY + (int) Math.round(n * 4);

                chunkData.setBlock(x, minY, z, Material.BEDROCK);
                for (int y = minY + 1; y < height - 1; y++) {
                    chunkData.setBlock(x, y, z, Material.STONE);
                }
                if (height - 1 >= minY + 1) {
                    chunkData.setBlock(x, height - 1, z, Material.DIRT);
                }
                chunkData.setBlock(x, height, z, Material.GRASS_BLOCK);
            }
        }
    }

    @Override
    public List<BlockPopulator> getDefaultPopulators(World world) {
        return List.of(new CardDimensionOrePopulator(surfaceY), new CardDimensionTreePopulator(surfaceY));
    }

    @Override
    public Location getFixedSpawnLocation(World world, Random random) {
        // A safe fallback vanilla spawn point; the plugin's own /gambit spawn and
        // first-join logic use the precise "in front of the portal" coordinate
        // tracked separately by CardDimensionManager, which is more exact than this.
        return new Location(world, 0.5, surfaceY + 1, 0.5);
    }

    @Override
    public BiomeProvider getDefaultBiomeProvider(WorldInfo worldInfo) {
        return new BiomeProvider() {
            @Override
            public Biome getBiome(WorldInfo worldInfo, int x, int y, int z) {
                // See the bundled datapack - this biome's colors are overridden to
                // purple specifically for this dimension, and the_void is never
                // naturally generated by vanilla anywhere else, so this is safe.
                return Biome.THE_VOID;
            }

            @Override
            public List<Biome> getBiomes(WorldInfo worldInfo) {
                return List.of(Biome.THE_VOID);
            }
        };
    }
}
