package com.gambitsmp.dimension;

import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.block.Biome;
import org.bukkit.generator.BiomeProvider;
import org.bukkit.generator.BlockPopulator;
import org.bukkit.generator.ChunkGenerator;
import org.bukkit.generator.WorldInfo;

import java.util.List;
import java.util.Random;

/**
 * CardDimension's generator.
 *
 * Explicitly opts in to every vanilla generation phase (noise/surface/caves/
 * decorations/mobs/structures - see the shouldGenerateX overrides below), so
 * vanilla generates the actual terrain shape itself using WorldType.AMPLIFIED
 * (set where this world is created in CardDimensionManager). An earlier version of
 * this class left those methods un-overridden assuming they defaulted to "on" -
 * they actually default to false, which produced a completely empty void world.
 *
 * On top of vanilla's terrain shape, this class contributes three things:
 *
 * - getDefaultBiomeProvider(): forces the whole world to report as the_void, whose
 *   colors are overridden purple by the bundled datapack (see CardDimensionManager
 *   and data/minecraft/worldgen/biome/the_void.json).
 * - getDefaultPopulators(): scattered ores minus diamond plus Ancient Debris, and
 *   sparse spruce trees. (Vanilla's own ore/vegetation features don't run here
 *   anyway, since the_void's overridden biome definition has an empty features
 *   list - so this populator is the only source of ores/trees, not an addition on
 *   top of vanilla ones.)
 * - getFixedSpawnLocation(): a harmless generic fallback; the plugin's own
 *   /gambit spawn and first-join logic use the precise "in front of the portal"
 *   location tracked separately by CardDimensionManager instead.
 */
public class CardDimensionGenerator extends ChunkGenerator {

    private final int surfaceY;

    public CardDimensionGenerator(int surfaceY) {
        this.surfaceY = surfaceY;
    }

    // IMPORTANT: these all default to FALSE when left un-overridden - omitting them
    // (as an earlier version of this class did) produces a completely empty void
    // world, since nothing then generates noise/surface/caves/decorations/mobs/
    // structures at all. Explicitly opting in to every vanilla phase is what
    // actually makes WorldType.AMPLIFIED (set in CardDimensionManager) take effect.
    @Override
    public boolean shouldGenerateNoise() {
        return true;
    }

    @Override
    public boolean shouldGenerateSurface() {
        return true;
    }

    @Override
    public boolean shouldGenerateCaves() {
        return true;
    }

    @Override
    public boolean shouldGenerateDecorations() {
        return true;
    }

    @Override
    public boolean shouldGenerateMobs() {
        return true;
    }

    @Override
    public boolean shouldGenerateStructures() {
        return true;
    }

    @Override
    public List<BlockPopulator> getDefaultPopulators(World world) {
        return List.of(new CardDimensionOrePopulator(surfaceY), new CardDimensionTreePopulator(surfaceY));
    }

    @Override
    public Location getFixedSpawnLocation(World world, Random random) {
        return new Location(world, 0.5, surfaceY + 1, 0.5);
    }

    @Override
    public BiomeProvider getDefaultBiomeProvider(WorldInfo worldInfo) {
        return new BiomeProvider() {
            @Override
            public Biome getBiome(WorldInfo worldInfo, int x, int y, int z) {
                // See the bundled datapack - this biome's colors (grass, foliage,
                // water) are overridden purple, and the_void is never naturally
                // generated by vanilla anywhere else, so this is safe.
                return Biome.THE_VOID;
            }

            @Override
            public List<Biome> getBiomes(WorldInfo worldInfo) {
                return List.of(Biome.THE_VOID);
            }
        };
    }
}
