package com.gambitsmp.dimension;

import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.block.Biome;
import org.bukkit.generator.BiomeProvider;
import org.bukkit.generator.BlockPopulator;
import org.bukkit.generator.ChunkGenerator;
import org.bukkit.generator.WorldInfo;

import java.util.List;
import java.util.Random;

/**
 * CardDimension's generator.
 *
 * Deliberately minimal now: this does NOT override shouldGenerateNoise/Surface/
 * Bedrock/Caves/Decorations, so all of those default to true and vanilla generates
 * the actual terrain shape itself (using WorldType.AMPLIFIED, set where this world
 * is created in CardDimensionManager) - this replaced an earlier fully hand-rolled
 * terrain generator that was the single highest-risk, most failure-prone part of
 * this whole plugin. Letting vanilla do the terrain shape removes that risk almost
 * entirely; this class now only contributes three things:
 *
 * - getDefaultBiomeProvider(): forces the whole world to report as the_void, whose
 *   colors are overridden purple by the bundled datapack (see CardDimensionManager
 *   and data/minecraft/worldgen/biome/the_void.json).
 * - getDefaultPopulators(): scattered ores minus diamond plus Ancient Debris, and
 *   sparse spruce trees. (Vanilla's own ore/vegetation features don't run here
 *   anyway, since the_void's overridden biome definition has an empty features
 *   list - so this populator is the only source of ores/trees, not an addition on
 *   top of vanilla ones.)
 * - getFixedSpawnLocation(): a harmless generic fallback; the plugin's own
 *   /gambit spawn and first-join logic use the precise "in front of the portal"
 *   location tracked separately by CardDimensionManager instead.
 */
public class CardDimensionGenerator extends ChunkGenerator {

    private final int surfaceY;

    public CardDimensionGenerator(int surfaceY) {
        this.surfaceY = surfaceY;
    }

    @Override
    public List<BlockPopulator> getDefaultPopulators(World world) {
        return List.of(new CardDimensionOrePopulator(surfaceY), new CardDimensionTreePopulator(surfaceY));
    }

    @Override
    public Location getFixedSpawnLocation(World world, Random random) {
        return new Location(world, 0.5, surfaceY + 1, 0.5);
    }

    @Override
    public BiomeProvider getDefaultBiomeProvider(WorldInfo worldInfo) {
        return new BiomeProvider() {
            @Override
            public Biome getBiome(WorldInfo worldInfo, int x, int y, int z) {
                // See the bundled datapack - this biome's colors (grass, foliage,
                // water) are overridden purple, and the_void is never naturally
                // generated by vanilla anywhere else, so this is safe.
                return Biome.THE_VOID;
            }

            @Override
            public List<Biome> getBiomes(WorldInfo worldInfo) {
                return List.of(Biome.THE_VOID);
            }
        };
    }
}
